### PR TITLE
Add `header.png` and centralise headings

### PR DESCRIPTION
**Pull request by src4026**

### CODE REVIEW

**Comment by src4026** [comment]
Ignore the opening and closing.

**Review by a-blob — CHANGES_REQUESTED** [review]
I'd recommend putting the image inside a folder. Another choice is to save the image to GitHub and use it from there. 
The header image license needs to be added here too.
>You must give [appropriate credit](https://creativecommons.org/licenses/by/3.0/#), provide a link to the license, and [indicate if changes were made](https://creativecommons.org/licenses/by/3.0/#).

**Comment by a-blob** [comment]
> Ignore the opening and closing.

~~You closed and opened it again to get the `Quickdraw` badge, right?~~

**Comment by a-blob** [comment]
The header image license needs to be added here too.

**Comment by src4026** [comment]
Oops, I edited your message on accident.

Ah, sorry, I didn't pay attention to that :sweat_smile: Also, I don't have electricity here ATM, I'll do it soon.

**Comment by src4026** [comment]
Sorry for that, I should pay attention to when I do these things. I believe it is now done :+1:

**Comment by src4026** [comment]
> I'd recommend putting the image inside a folder. Another choice is to save the image to GitHub and use it from there. The header image license needs to be added here too.
> 
> > You must give [appropriate credit](https://creativecommons.org/licenses/by/3.0/#), provide a link to the license, and [indicate if changes were made](https://creativecommons.org/licenses/by/3.0/#).

I prefer the image folder, since I used that on mine as well. Done that for now.

**Comment by src4026** [comment]
https://github.com/CTF-handbooks/map-maker-handbook/pull/6/commits/f519024c63a276c6646623d7f1154eb18e7e96b9 changes the handbook name in the README.md to how it is in maker-handbook.md

**Pull request merged**
